spring:
  cloud:
    stream:
      bindings:
        to-listing-request:
          destination: to-listing-request
          group: stream-to-listing-request
          producer:
            required-groups: stream-to-listing-request
        to-listing-reply:
          destination: to-listing-reply
          group: gateway-to-listing-reply

server:
  port: 9002
